apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness
spec:
  type: NodePort
  selector:
    app: aceest-fitness
    color: blue   # initial live color
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080